"""change bid_attribute.num_val to currency type

Revision ID: 077024522d30
Revises: c0e48290a8c3
Create Date: 2024-04-08 18:45:28.440731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "077024522d30"
down_revision: Union[str, None] = "c0e48290a8c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "bid_attribute",
        "num_val",
        existing_type=sa.INTEGER(),
        type_=sa.Numeric(precision=15, scale=2),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "bid_attribute",
        "num_val",
        existing_type=sa.Numeric(precision=15, scale=2),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
