"""make option value unique to bid attribute type

Revision ID: 1883228aede5
Revises: d54eba4b543e
Create Date: 2024-04-18 23:23:55.434193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1883228aede5"
down_revision: Union[str, None] = "d54eba4b543e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        None,
        table_name="bid_attribute_option",
        columns=["attribute_type_id", "value"],
        schema="lookup",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "bid_attribute_option", schema="lookup")
    # ### end Alembic commands ###
