"""change requests from meeting 4/9/24

Revision ID: 4ed63c505ea3
Revises: 077024522d30
Create Date: 2024-04-15 00:00:47.854226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4ed63c505ea3"
down_revision: Union[str, None] = "077024522d30"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bid_status",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("value", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("value"),
        schema="lookup",
    )
    op.create_table(
        "job_status",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("value", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("value"),
        schema="lookup",
    )
    op.create_table(
        "comment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(length=255), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("bid_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["bid_id"],
            ["bid.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("bid", sa.Column("bid_status_id", sa.Integer(), nullable=True))
    op.add_column("bid", sa.Column("job_status_id", sa.Integer(), nullable=True))
    op.add_column(
        "bid",
        sa.Column("desired_margin", sa.Numeric(precision=15, scale=2), nullable=True),
    )
    op.create_foreign_key(
        None, "bid", "bid_status", ["bid_status_id"], ["id"], referent_schema="lookup"
    )
    op.create_foreign_key(
        None, "bid", "job_status", ["job_status_id"], ["id"], referent_schema="lookup"
    )
    op.alter_column("bid", "original_cost", new_column_name="final_cost")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("bid", "final_cost", new_column_name="original_cost")
    op.drop_constraint(None, "bid", type_="foreignkey")
    op.drop_constraint(None, "bid", type_="foreignkey")
    op.drop_column("bid", "desired_margin")
    op.drop_column("bid", "final_cost")
    op.drop_column("bid", "job_status_id")
    op.drop_column("bid", "bid_status_id")
    op.drop_table("comment")
    op.drop_table("job_status", schema="lookup")
    op.drop_table("bid_status", schema="lookup")
    # ### end Alembic commands ###
